spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root-pass
  batch:
    jdbc:
      initialize-schema: never
    job:
      names: ${job.name:NONE}